name: dart_pdfium
description: PDFium FFI for Dart.
version: 0.0.1
author: z10g
homepage: elmpark.io

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  ffi: ^0.1.3
  image: ^2.1.14
  equatable: ^1.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.15.2
  ffi_tool:
    git: git@github.com:dart-interop/ffi_tool.git
  ffigen: ^1.0.5

ffigen:
  output: 'lib/ffi_gen/ffi_gen.dart'
  headers:
    entry-points:
      - '/Users/zhonghua/programs/pdfium/include/*.h'
